---
title: "Uso Avanzado de Sistemas de Información Geográfica (SIG) (IMSE1017)"
subtitle: "Ing. en Medio Ambiente Y Sustentabilidad"
author: "Dr. Francisco Zambrano"
lang: es
theme: default
format:
  html:
    number-sections: true
    number-depth: 2
    smooth-scroll: true
    code-fold: true
    toc: true
    html-math-method: katex
---

## Reseña

En este repositorio se pone a disposición de los alumnos de Ing. en Medio Ambiente y sustentabilidad de la UMayor, las clases, laboratorios y material que se utilizará en la asignatura de SIG Avanzado. Este repositorio está creado con [quarto](https://quarto.org/) por medio del software `R`.

## Clases

I) Unidad 1: Manejo de  datos SIG  con R.
    
    1) [Presentación curso](Clase1/slides_clase11.html)  
    2) [Introducción a `R` para análisis espacial](Clase1/slides_clase12.html)   
    3) [`R`: Tipos y estructuras de datos](Clase1/slides_clase13.html)   
    4) [Manipulación de datos](Clase2/slides_clase21.html)
    5) [Introducción al análisis espacial con R](Clase3/slides_clase31.html)
    6) [Datos Espaciales en R](Clase3/slides_clase32.html)
    
    
## Talleres

1) [Taller 1: Tipos y estructuras de datos en R](Talleres/Taller1/taller1.html)
2) [Taller 2: Datos climáticos R](Talleres/Taller2/Taller2.html)

## Material

- R
  - [SWIRL](https://swirlstats.com/)
  - [Quick-R](https://www.statmethods.net/)

- R-Spatial
  - [r-spatial](https://www.r-spatial.org/) - Edzer Pebesma
  - [rspatial](https://www.rspatial.org/) - Robert Hijmans

- Libros R-Spatial
  - [Applied Spatial Data Analysis with R. Roger Bivand, Edzer Pebesma, Virgilio Gómez-Rubio.](http://gis.humboldt.edu/OLM/r/Spatial%20Analysis%20With%20R.pdf)
  - [Geocomputation with R. Robin Lovelace, Jakub Nowosad, Jannes Muenchow](https://geocompr.robinlovelace.net/)
  - [Spatial Data Science](https://keen-swartz-3146c4.netlify.app/). Edzer Pebesma y Roger Bivand. Estado: en desarrollo
  

