---
title: "Evaluación 1 talleres"
subtitle: "Uso Avanzado de SIG"
author: "Dr. Francisco Zambrano"
format: html
lang: es
editor: visual
---

## Datos

En el campus virtual en la sección `evaluaciones/evaluacion 1 talleres`, se encuentran los siguientes set de datos:

- `metadata_estaciones_agrometAPI.csv`: archivo que contiene información de ubicación, nombre, insitución, etc; para 417 estaciones de la red [agromet](https://www.agromet.cl). 

- `archivos_csv_por_estacion.zip`: archivo comprimido que contiene 49 archivos en formato delimitado por comma (csv) con datos climáticos correspondientes a 49 estaciones en Chile.



## Ejercicios

Escriba un script en R que permita realizar lo siguiente:

1. Cargue en R el archivo `metadata_estaciones_agrometAPI.csv` y asignelo al objeto `data_info`.

2. Cuál es el nombre de las columnas de `data_info`

3. Seleccione de `data_info` la estación que se le asigno en el campus virtual. Indique el nombre, comuna, región, latitud y longitud de la estación.


4. Cargar en R el archivo '.csv' correspondiente a los datos climáticos y asignelo al objeto `data`. Debe elegir el archivo correspondiente al código de la estación de acuerdo a lo que se indica en el campus virtual `Evaluaciones/Evaluación 1 talleres`. Nota: Para los siguientes ejercicios debe seguir trabajando con estos datos.

5. Genere un resumen de la estructura de datos del objeto `data`, en el que se debe poder identificar la clase de objeto, la cantidad de variables y observaciones; y la clase de objeto de cada variable.

6. Haga un resumen estadístico de todas las variables que contiene `data`.

7. Indique entre que rango de fechas se encuentran las observaciones del objeto `data`.

8. Cree un objeto `data_temp` en el que se guarde un subconjunto de el objeto `data` que contenga las variables de `fecha_hora`,`temp_promedio_aire`, `temp_minima`, `temp_maxima`.

9. Cree un objeto `data_temp_enero` en el que se guarde un subconjunto del objeto `data_temp`, que debe contener todas las observaciones del mes de enero 2021.

10. Cuál es la temperatura promedio, máxima y mínima del mes de enero 2021.

11. Cree una matriz de correlación entre las variables de temperatura del objeto `data_temp`. No considere los valores NA en el cálculo.





